# Generated by Django 4.0.4 on 2022-05-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlShortner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MainUrl', models.URLField(null=True)),
                ('uuid', models.CharField(max_length=15, unique=True)),
                ('Views', models.IntegerField(default=0)),
                ('Active_Url', models.BooleanField(default=False, null=True)),
                ('Paid', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-Views', '-Paid'],
            },
        ),
    ]
